package com.kerrysgame.game

val kerryQuotes = listOf(
    "Choppin' wood like it's my therapy... still cheaper than a shrink.",
    "This tree owes me money. Time to collect.",
    "Another log, another day I didn't get fired. Small wins.",
    "If trees could scream, I'd be a war criminal. Good thing they just rustle.",
    "Swinging an axe builds character. Mostly upper body character. And rage.",
    "I'm basically a vegan's worst nightmare... with better jokes.",
    "This is what happens when you skip leg day but never skip axe day.",
    "Trees hate me. The feeling is mutual.",
    "Keep chopping, maybe I'll afford therapy by 2047.",
    "I'd say this is pointless, but at least the wood disagrees.",
    "You call it deforestation. I call it cardio.",
    "Every ring in this trunk is a year it should've minded its business.",
    "I don't have anger issues. I have axe solutions.",
    "My white '78 Jeep is lifted. My standards are not.",
    "Blue letters on the Jeep say 'KERRY.' Subtle branding, zero shame.",
    "This forest is basically my unpaid internship.",
    "Knock knock. It's me. The consequences.",
    "I split logs and expectations at the same time.",
    "Axe me if I care. Actually don't. I'm busy.",
    "If sarcasm were fuel, my Jeep would never run dry.",
    "These logs are getting chopped harder than my life choices.",
    "I came, I saw, I made mulch.",
    "I swing therefore I am. Philosophers can fight me.",
    "Some people meditate. I commit timber violence.",
    "The tree had one job: stand there. It failed.",
    "If effort had splinters, it'd look like this.",
    "I don't chase dreams. I chase combo multipliers.",
    "One chop at a time, one bad decision at a time.",
    "My retirement plan is wood. Like, literally wood.",
    "This boss tree is just a regular tree with delusions.",
    "The winter logs are frozen, like my emotional availability.",
    "Summer logs burn faster. So does my patience.",
    "If you're waiting for a moral, this ain't that kind of forest.",
    "I've got 99 problems and this trunk is all of them.",
    "Wood chips everywhere. That's confetti for poor choices.",
    "The axe is sharp, unlike my social skills.",
    "Every tap helps. Not emotionally, but mechanically.",
    "Even the squirrels are judging my work ethic.",
    "I'm not overpowered. The trees are underprepared.",
    "Call me old-fashioned, but I solve problems with steel.",
    "This grind is endless, just like my sarcasm.",
    "Achievement unlocked: still not impressed.",
    "When life gives you trees, make sawdust.",
    "I'd stop, but the leaderboard won't insult itself.",
    "You tap, I swing, everybody loses except my wood count."
)

val kerrySummaryQuotes = listOf(
    "Ten waves down. My arm filed a complaint.",
    "Summary: trees 0, me 1, therapy still 0.",
    "Another milestone. Still not impressed.",
    "Boss tree deleted. You're welcome, forest.",
    "Numbers go up. Satisfaction stays flat.",
    "We did it. It felt exactly like work.",
    "That was cardio. The boring kind.",
    "Nice streak. Let me pretend I care.",
    "Wave cleared. Ego not.",
    "I would celebrate, but I'm allergic to joy."
)